objective:
  - reconstruction_objective

dataset:
  - radio_interferometry:
      image_size: 256
      fits_size: "1024"
      noise_level: 0.1
      seed: 42
      use_gpus: true
      number_of_time_steps: 64

solver:
  - PnP:
      denoiser: drunet
      distribute_physics: False
      distribute_denoiser: False
      init_method: ["adjoint"]
      norm_strategy: ["dynamic"]
      slurm_gres, slurm_ntasks_per_node, distribute_physics, distribute_denoiser, patch_size, denoiser_sigma: [
        ["gpu:0", 4, true, true, [128], 0.001]
      ]
      
