objective:
  - reconstruction_objective

dataset:
  - radio_interferometry:
      fits_name : "m101_g.fits"
      image_size: 4000
      noise_level: 0.1
      simulator_hash: "c48ba85bb7326b3345d92135eaf4143d"

solver:
  - PnP:
      denoiser: drunet
      denoiser_sigma: [0.2]
      distribute_physics: False
      distribute_denoiser: False
      init_method: ["adjoint"]
      norm_strategy: ["dynamic"]
      slurm_gres, slurm_ntasks_per_node, distribute_physics, distribute_denoiser, patch_size, denoiser_sigma: [
        ["gpu:0", 4, true, true, [512], 0.01]
      ]
      
