objective:
  - reconstruction_objective

dataset:
  - tomography_2d:
      image_size: 128
      batch_size: 1
      num_operators: 1
      num_angles: 30
      noise_level: 0.01
      seed: 42

solver:
  - PnP:
      denoiser: drunet
      denoiser_sigma: 0.01
      step_size: 0.1
      init_method: ["zeros"]
      slurm_gres, slurm_ntasks_per_node, slurm_nodes, distribute_physics, distribute_denoiser, patch_size, overlap, max_batch_size: [
        ["gpu:1", 1, 1, false, false, 0, 0, 0],
      ]

max-runs: 10
n-repetitions: 1
plot: true
html: true
